services:
  redis:
    image: redis:7.4
    networks:
      - identidock-net
  dnmonster:
    image: amouat/dnmonster:1.1
    networks:
      - identidock-net
  app:
    build: .
    container_name: app
    networks:
      - identidock-net
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
  reverse-proxy:
    build: ../reverse-proxy/
    container_name: reverse-proxy
    networks:
      - identidock-net
    ports:
      - "8000:80"
networks:
  identidock-net:
    driver: bridge
    external: true 
